global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'MyAppMetrics'
    scheme: http
    metrics_path: '/actuator/prometheus'

    # Override global interval for this job
    scrape_interval: 3s
    scrape_timeout: 2s

    static_configs:
      - targets:
          - 'host.docker.internal:8080'
        labels:
          application: 'My Spring Boot Application'

    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: myapp-backend